language: ruby
services:
  - postgresql
env:
  - "RAILS_ENV=test"
before_script:
  - RAILS_ENV=test rake db:create db:migrate
addons:
  postgresql: "10.3"
  code_climate:
    repo_token:
after_success:
  - bundle exec codeclimate-test-reporter